name: Arduino CLI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: esp32-evb
            fqbn: esp32:esp32:esp32-evb
            board_options: "PartitionScheme=min_spiffs"

          - name: esp32-devkit
            fqbn: esp32:esp32:esp32
            board_options: "PartitionScheme=min_spiffs"

          - name: due
            fqbn: arduino:sam:arduino_due_x
            extra_flags: ""
            board_options: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv ./bin/arduino-cli /usr/local/bin/arduino-cli

      - name: Install platform cores
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli core install arduino:sam

      - name: Install Ethernet library
        run: |
          arduino-cli lib install Ethernet

      - name: Setup config files
        run: |
          cp BSB_LAN/BSB_LAN_config.h.default BSB_LAN/BSB_LAN_config.h
          cp BSB_LAN/BSB_LAN_custom_defs.h.default BSB_LAN/BSB_LAN_custom_defs.h

      - name: Compile for ${{ matrix.name }}
        run: |
          arduino-cli compile \
            --fqbn ${{ matrix.fqbn }} \
            --libraries BSB_LAN/libraries \
            --build-property build.extra_flags="${{ matrix.extra_flags }}" \
            --board-options ${{ matrix.board_options }} \
            BSB_LAN