name: Update Compile Time

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-compiletime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch full history
        run: |
          git fetch origin

      - name: Update COMPILETIME and optionally PATCH
        run: |
          FILE="BSB_LAN/bsb-version.h"
          REMOTE_FILE=$(mktemp)
          git show origin/master:$FILE > $REMOTE_FILE || touch $REMOTE_FILE

          get_define() { grep "#define $1" "$2" | cut -d '"' -f 2; }

          PATCH_LOCAL=$(get_define PATCH $FILE)
          PATCH_REMOTE=$(get_define PATCH $REMOTE_FILE)

          MINOR_LOCAL=$(get_define MINOR $FILE)
          MINOR_REMOTE=$(get_define MINOR $REMOTE_FILE)

          MAJOR_LOCAL=$(get_define MAJOR $FILE)
          MAJOR_REMOTE=$(get_define MAJOR $REMOTE_FILE)

          TIMESTAMP=$(git show -s --format=%cd --date=format:'%Y%m%d%H%M%S' HEAD)

          # Always update COMPILETIME
          sed -i 's/^#define COMPILETIME .*$/#define COMPILETIME "'"$TIMESTAMP"'"/' $FILE

          # Conditionally update PATCH
          if [ "$MAJOR_LOCAL" = "$MAJOR_REMOTE" ] && \
             [ "$MINOR_LOCAL" = "$MINOR_REMOTE" ] && \
             [ "$PATCH_LOCAL" = "$PATCH_REMOTE" ]; then
            NEW_PATCH=$((PATCH_LOCAL + 1))
            echo "Auto-incrementing PATCH to $NEW_PATCH"
            sed -i "s/#define PATCH \".*\"/#define PATCH \"$NEW_PATCH\"/" $FILE
          else
            echo "Manual version bump detected – only updating COMPILETIME"
          fi

      - name: Configure git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add BSB_LAN/bsb-version.h

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update COMPILETIME and optionally PATCH [automated]"
            git push origin HEAD:master
          fi