name: Update Compile Time

on: [push, pull_request]

jobs:
  update-compiletime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup workspace
        run: |
          sudo rm -rf * .[!.]* ..?*  # Removes all files in the current directory, including hidden ones.

      - name: Reclone the repository
        run: |
          git clone https://github.com/fredlcore/BSB-LAN.git .
          # Assuming the repository root is where you work directly; adjust if necessary.

      - name: Setup Git Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update compile time in bsb-version.h
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)  # Generates a timestamp.
          sed -i "s/#define COMPILETIME .*/#define COMPILETIME \"$TIMESTAMP\"/" BSB_LAN/bsb-version.h
          cat BSB_LAN/bsb-version.h  # Optional: for debugging, view the contents of the file.

      - name: Commit and push changes
        run: |
          git add BSB_LAN/bsb-version.h
          git commit -m "Update COMPILETIME to $TIMESTAMP"
          git push origin main
